name: Kkubex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  localstorage: ^3.0.1+4
  dio: ^3.0.8
  provider: ^4.0.4
  fluro: ^1.6.0
  get_it: ^3.0.3
  fluttertoast: ^4.0.1
  flutter_screenutil: ^1.1.0
  cookie_jar: ^1.0.0
  path_provider: ^1.6.5
  dio_cookie_manager: ^1.0.0
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - image/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700